spring:
  datasource:
    driver-class-name : org.postgresql.Driver
    url : jdbc:postgresql://postgres:5432/Yandex_Translator
    username : postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true

translator:
  yandex:
    api-key : <>
    api-url : https://translate.api.cloud.yandex.net/translate/v2/translate
    api-folder-id : <>